### PR TITLE
Add a "/. mute" so players can mute the clan chat.

### PR DESCRIPTION
**Pull request by matgsan**
Also if a player has the permission "simpleclans.admin.all-seeing-eye" will mute all clans chats!

### CODE REVIEW

**Comment by phaed420** [comment]
Good feature, can't merge this version of it though.  If you look at the changes it messes up all the formatting.

**Comment by matgsan** [comment]
Yeah i know i clicked by accident on format of NetBeans, I will remake so i can do a pull request again. What do u think?

**Comment by phaed420** [comment]
Go for it.

**Comment by matgsan** [comment]
Done it is good now?

**Pull request merged**
